- name: Build APK (debug)
        run: |
          cd app
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SixStringBootCamp
          path: app/build/outputs/apk/debug/app-debug.apk
